// @generated by tools/gen_palettes.py from pmmp/BedrockData (CC0-1.0).
// Do not edit by hand.

static P_BEDROCK_1_21_50: &[u8] = include_bytes!("../data/palettes/bedrock-1.21.50.bin");
static P_BEDROCK_1_21_60: &[u8] = include_bytes!("../data/palettes/bedrock-1.21.60.bin");
static P_BEDROCK_1_21_70: &[u8] = include_bytes!("../data/palettes/bedrock-1.21.70.bin");
static P_BEDROCK_1_21_80: &[u8] = include_bytes!("../data/palettes/bedrock-1.21.80.bin");
static P_BEDROCK_1_21_100: &[u8] = include_bytes!("../data/palettes/bedrock-1.21.100.bin");
static P_BEDROCK_1_21_111: &[u8] = include_bytes!("../data/palettes/bedrock-1.21.111.bin");
static P_BEDROCK_1_26_10: &[u8] = include_bytes!("../data/palettes/bedrock-1.26.10.bin");
static P_BEDROCK_1_26_20: &[u8] = include_bytes!("../data/palettes/bedrock-1.26.20.bin");
static P_BEDROCK_1_26_30: &[u8] = include_bytes!("../data/palettes/bedrock-1.26.30.bin");

/// `(first protocol, BedrockData tag, zlib-compressed palette, state count)`,
/// sorted by protocol.
#[rustfmt::skip]
pub(crate) static PALETTES: &[(i32, &str, &[u8], usize)] = &[
    (766, "bedrock-1.21.50", P_BEDROCK_1_21_50, 15162),
    (776, "bedrock-1.21.60", P_BEDROCK_1_21_60, 15168),
    (786, "bedrock-1.21.70", P_BEDROCK_1_21_70, 15237),
    (800, "bedrock-1.21.80", P_BEDROCK_1_21_80, 15253),
    (818, "bedrock-1.21.90", P_BEDROCK_1_21_80, 15253),
    (819, "bedrock-1.21.93", P_BEDROCK_1_21_80, 15253),
    (827, "6.0.0+bedrock-1.21.100", P_BEDROCK_1_21_100, 15285),
    (844, "bedrock-1.21.111", P_BEDROCK_1_21_111, 15845),
    (859, "bedrock-1.21.120", P_BEDROCK_1_21_111, 15845),
    (897, "bedrock-1.21.130", P_BEDROCK_1_21_111, 15845),
    (924, "bedrock-1.26.0", P_BEDROCK_1_21_111, 15845),
    (944, "bedrock-1.26.10", P_BEDROCK_1_26_10, 15846),
    (975, "bedrock-1.26.20", P_BEDROCK_1_26_20, 16899),
    (1001, "bedrock-1.26.30", P_BEDROCK_1_26_30, 16913),
];
