#!/usr/bin/env python3
"""Generate src/block_table.rs from PMMP BedrockData's block_properties_table.json.

BedrockData is CC0-1.0 (https://github.com/pmmp/BedrockData).
Usage: python3 tools/gen_block_table.py path/to/block_properties_table.json [tag]
"""
import json
import sys

src = sys.argv[1]
tag = sys.argv[2] if len(sys.argv) > 2 else "unknown"
data = json.load(open(src))
rows = []
for name, p in data.items():
    short = name.removeprefix("minecraft:")
    rows.append((short, float(p["hardness"]), float(p["friction"]), int(round(float(p["brightness"]) * 15))))
rows.sort(key=lambda r: r[0])

def f(v):
    s = repr(round(v, 4))
    return s if "." in s or "e" in s else s + ".0"

out = [
    "// @generated by tools/gen_block_table.py from pmmp/BedrockData " + tag + " (CC0-1.0).",
    "// Do not edit by hand. Columns: name (without `minecraft:`), hardness, friction, light emission.",
    "",
    "#[rustfmt::skip]",
    "pub(crate) static BLOCK_TABLE: &[(&str, f32, f32, u8)] = &[",
]
for n, h, fr, l in rows:
    out.append(f'    ("{n}", {f(h)}, {f(fr)}, {l}),')
out.append("];")
open("src/block_table.rs", "w").write("\n".join(out) + "\n")
print(len(rows), "blocks")
